### PR TITLE
Add Google client id and secret to .env file

### PR DESCRIPTION
**Pull request by SEdilson**

### CODE REVIEW

**Review by jugaldb — COMMENTED** [review]
Hey @SEdilson  I know the dev.env file wasn't in .gitignore but it is a good practise to move it in .gitignore, before you do that, revoke your keys and make new ones, dont commit before moving into .gitignore and add the dev.env file location and specifics to the readme , the  code looks good, just make these changes

Thanks

**Comment by SEdilson** [comment]
Ok @jugaldb

**Review by jugaldb — APPROVED** [review]
Great job @SEdilson , Approved

**Comment by SEdilson** [comment]
Thanks @jugaldb

**Pull request merged**
